// SPDX-FileCopyrightText: 2026 agentc Authors
//
// SPDX-License-Identifier: MIT

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResolvedContextBlock {
    /// Block label.
    pub name: String,
    /// Optional description of the block.
    pub description: Option<String>,
    /// Files generated by this block, keyed by output path.
    pub generates: HashMap<String, ResolvedContextBlockTemplate>,
    /// Extension point contributions, keyed by extension point name.
    pub contributes: HashMap<String, ResolvedContextBlockTemplate>,
    /// Additional Cargo.toml dependencies this block requires, keyed by crate name.
    pub dependencies: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResolvedContextBlockTemplate {
    /// Original path as declared in the manifest.
    pub path: String,
    /// Raw template content.
    pub content: String,
}
