// SPDX-FileCopyrightText: 2026 agentc Authors
//
// SPDX-License-Identifier: MIT

use sanitizer::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use validator::Validate;

#[derive(Debug, Clone, Serialize, Deserialize, Validate, Sanitizer)]
pub struct ManifestBlock {
    /// Optional description of the block.
    #[serde(default)]
    #[validate(length(min = 1))]
    #[sanitizer(trim)]
    pub description: Option<String>,
    /// Files to be generated by this block, keyed by output path.
    #[serde(default)]
    pub generates: HashMap<String, String>,
    /// Extension point contributions, keyed by extension point name.
    #[serde(default)]
    pub contributes: HashMap<String, String>,
    /// Additional Cargo.toml dependencies this block requires, keyed by crate name.
    #[serde(default)]
    pub dependencies: HashMap<String, String>,
}
