version: '3'

silent: true

includes:
  version:
    taskfile: .taskfile/version.yml
  rust:
    taskfile: .taskfile/rust.yml
  devtools:
    taskfile: .taskfile/devtools.yml
  docker:
    taskfile: .taskfile/docker.yml
  database:
    taskfile: .taskfile/database.yml

tasks:
  run:
    cmds:
      - cargo run --bin agentc -- {{.CLI_ARGS}}
