[package]
name = "agentc-blocks"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
agentc-compiler = { path = "../agentc-compiler", version = "0.3.0" }

tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

convert_case = { workspace = true }

flate2 = { version = "1.0" }
tar = { version = "0.4" }

proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "2", features = ["full"] }

[build-dependencies]
toml_edit = "0.25.11"
tar = "0.4"
flate2 = "1.0"
ignore = "0.4"