[package]
name = "agentc-mcp"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
agentc-telemetry = { path = "../agentc-telemetry", version = "0.3.1" }
agentc-agent = { path = "../agentc-agent", version = "0.3.1" }

rmcp = { version = "1.3", features = [
    "client",
    "reqwest",
    "transport-child-process",
    "transport-streamable-http-client-reqwest",
] }
reqwest = { version = "0.13", features = ["hickory-dns", "json", "stream"] }

tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }