// SPDX-FileCopyrightText: 2026 agentc Authors
//
// SPDX-License-Identifier: MIT

use serde::{Deserialize, Serialize};

use crate::generator::extension::reducers;

/// Manifest for a template block, defining its files, extension points, and slot fills.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplateBlockManifest {
    pub id: String,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub files: Vec<FileSpec>,
    #[serde(default)]
    pub extension_points: Vec<ExtensionPointSpec>,
    #[serde(default)]
    pub slot_fills: Vec<SlotFillSpec>,
}

/// Specification for a file to be generated by a template block.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileSpec {
    /// The output path for the generated file. Interpolation is supported
    /// with jinja2 syntax, e.g. `src/{{ name }}.rs`.
    pub path: String,
    /// The template content for the file. Interpolation is supported with jinja2 syntax.
    pub template: String,
    /// Optional condition expression that determines whether this file would be generated.
    /// Uses the CEL syntax and can reference any variables in the template context.
    /// If the condition evaluates to false, the file will be skipped.
    #[serde(default)]
    pub condition: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtensionPointSpec {
    /// The name of the extension point, which can be referenced by other blocks to extend it.
    pub name: String,
    /// How contributions are reduced to a final value. Defaults to concat.
    #[serde(default)]
    pub reducer: Reducer,
}

/// Reducer strategy to combine multiple contributions to an extension point into a single value.
#[derive(Default, Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Reducer {
    #[default]
    Concat,
    ConcatUnique,
    JoinComma,
    First,
    Last,
}

impl Reducer {
    pub fn as_fn(&self) -> fn(Vec<String>) -> String {
        match self {
            Reducer::Concat => reducers::concat,
            Reducer::ConcatUnique => reducers::concat_unique,
            Reducer::JoinComma => reducers::join_comma,
            Reducer::First => reducers::first,
            Reducer::Last => reducers::last,
        }
    }
}

/// Specification for a contribution this block makes into a named extension point.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlotFillSpec {
    /// The name of the extension point this contribution is for.
    pub point: String,
    /// The template content for this contribution. Interpolation is supported with jinja2 syntax.
    pub template: String,
    /// Optional condition expression that determines whether this contribution would be included.
    /// Uses the CEL syntax and can reference any variables in the template context.
    #[serde(default)]
    pub condition: Option<String>,
    /// Whether this generation fails when the target extension point does not exist.
    /// If false, this contribution is silently skipped.
    #[serde(default)]
    pub strict: bool,
}
