[package]
name = "agentc-tools"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ["bash", "python-rustpython"]
javascript = [
    "dep:agentc-executor-typescript",
]
python = ["dep:agentc-executor-python"]
python-rustpython = ["python", "agentc-executor-python/rustpython"]
python-cpython = ["python", "agentc-executor-python/pyo3"]
bash = [
    "dep:agentc-fs",
    "dep:agentc-http",
    "dep:base64",
    "dep:bashkit",
    "dep:uuid",
]

[dependencies]
agentc-agent = { path = "../agentc-agent", version = "0.3.1" }
agentc-fs = { path = "../agentc-fs", version = "0.3.1", optional = true }
agentc-http = { path = "../agentc-http", version = "0.3.1", default-features = false, features = ["client"], optional = true }
agentc-executor-typescript = { path = "../agentc-executor-typescript", version = "0.3.1", optional = true }
agentc-executor-python = { path = "../agentc-executor-python", version = "0.3.1", default-features = false, optional = true }

base64 = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }
sanitizer = { workspace = true }
json-patch = { workspace = true }

schemars = { workspace = true }

bashkit = { version = "0.17.1", default-features = false, features = ["tzdata"], optional = true }
