// SPDX-FileCopyrightText: 2026 agentc Authors
//
// SPDX-License-Identifier: MIT

use utoipa::{
    __dev::{SchemaReferences, Tags},
    Path,
    openapi::Components,
};
use utoipa_axum::router::OpenApiRouter;

/// Extension methods for [`OpenApiRouter`].
pub trait OpenApiRouterExt {
    /// Records the OpenAPI documentation for a `#[utoipa::path]` handler
    /// without registering a matching axum route.
    ///
    /// `P` is the `__path_<handler>` type generated by [`utoipa::path`]. Use
    /// this when a documented path cannot be expressed as an axum route.
    fn document<P>(self) -> Self
    where
        P: Path + SchemaReferences + for<'t> Tags<'t>;
}

impl<S> OpenApiRouterExt for OpenApiRouter<S>
where
    S: Clone + Send + Sync + 'static,
{
    fn document<P>(mut self) -> Self
    where
        P: Path + SchemaReferences + for<'t> Tags<'t>,
    {
        let openapi = self.get_openapi_mut();

        let mut schemas = Vec::new();
        P::schemas(&mut schemas);

        openapi
            .components
            .get_or_insert(Components::new())
            .schemas
            .extend(schemas);

        // The generated `operation()` omits the handler's `tag`; it is exposed
        // separately through `Tags::tags()`, so merge it in as `routes!` does.
        let mut operation = P::operation();

        let tags = P::tags();

        if !tags.is_empty() {
            operation
                .tags
                .get_or_insert(Vec::new())
                .extend(tags.iter().map(ToString::to_string));
        }

        openapi
            .paths
            .add_path_operation(P::path(), P::methods(), operation);

        self
    }
}
