[project]
name = "{{ name_snake }}"
version = "0.1.0"
description = ""
readme = "README.md"
authors = []
requires-python = ">=3.14"
dependencies = [
    "agentc-tdk @ git+https://github.com/agentc-sh/python-tdk.git@0.1.0"
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
# Hatch requires explicitly allowing direct references to git repositories.
allow-direct-references = true
