[package]
name = "agentc-executor-typescript"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = []

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }

thiserror = { workspace = true }

guestjs = { git = "ssh://git@github.com/wizrds/guestjs.git", rev = "0.1.3", features = ["tokio", "typescript", "llrt-buffer", "llrt-console"] }
