[package]
name = "agentc-model"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
agentc-telemetry = { path = "../agentc-telemetry", version = "0.2.1" }

tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

rig-core = { version = "0.39", features = ["derive", "rayon", "rmcp"] }
