// SPDX-FileCopyrightText: 2026 agentc Authors
//
// SPDX-License-Identifier: MIT

use utoipa::{
    Path,
    __dev::SchemaReferences,
    openapi::Components,
};
use utoipa_axum::router::OpenApiRouter;

/// Extension methods for [`OpenApiRouter`].
pub trait OpenApiRouterExt {
    /// Records the OpenAPI documentation for a `#[utoipa::path]` handler
    /// without registering a matching axum route.
    ///
    /// `P` is the `__path_<handler>` type generated by [`utoipa::path`]. Use
    /// this when a documented path cannot be expressed as an axum route — for
    /// example an A2A custom method such as `/tasks/{id}:cancel`, which
    /// `matchit` rejects — and the request is served by a different,
    /// matchit-valid route.
    fn document<P>(self) -> Self
    where
        P: Path + SchemaReferences;
}

impl<S> OpenApiRouterExt for OpenApiRouter<S>
where
    S: Clone + Send + Sync + 'static,
{
    fn document<P>(mut self) -> Self
    where
        P: Path + SchemaReferences,
    {
        let openapi = self.get_openapi_mut();

        let mut schemas = Vec::new();
        P::schemas(&mut schemas);

        openapi
            .components
            .get_or_insert(Components::new())
            .schemas
            .extend(schemas);

        openapi
            .paths
            .add_path_operation(P::path(), P::methods(), P::operation());

        self
    }
}
