name: default

on:
  pull_request:
    branches:
      - dev

jobs:
  dco:
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]')
    uses: ./.github/workflows/dco.yml
    permissions:
      contents: read
      pull-requests: read
    with:
      repository: ${{ github.repository }}
      pull-request-number: ${{ github.event.number }}
      skip-subject-regexes: |
        ^chore\(release\):
        ^Release Candidate [0-9a-f]+\.\.[0-9a-f]+ \(#[0-9]+\)$

  lint:
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]')
    needs: dco
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v3
        with:
          version: 3.43.3

      - name: Lint commit message
        run: |
          pip install gitlint
          git log -1 --pretty=%B | gitlint

      - name: Lint code
        run: task rust:lint

      - name: Format code
        run: task rust:fmt

  tests:
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v3
        with:
          version: 3.43.3

      - name: Unit tests - Compiler
        run: task rust:test:compiler

      - name: Unit tests - Runtime
        run: task rust:test:runtime
